### ISSUE TITLE
invert commands

### ISSUE THREAD

**Issue by t0b1nux** [brouberol/marcel#10]
Why not use something like busybox (check argv[0])  and use links to inverts commands.
So we could use ```chauffe marcel``` instead of ```marcel chauffe```.
What do you think ?

**Comment by brouberol** [comment]
That would require to provide an entry point for each command, instead of just providing ``marcel``, and could lead to some maintainability burden. You seem to like overcomplications, just like the French administration. I'm torn.

**Comment by t0b1nux** [comment]
No, you just need to check argv[0] and invert it with argv[1] in you program, It shoudd be fairly easy

**Comment by brouberol** [comment]
Let's take an example. I type the command ``chauffe marcel``, and I'd like it to run ``docker run``obviously. To do that, the ``chauffe``command must be linked to the ``marcel.py`` module (for example with an entry point in setup.py), along with all other docker commands we'd like to support.

Or I might not see something obvious?

**Comment by t0b1nux** [comment]
When you launch a program, argv[0] is the name of the program. So you could still use the same mapping technology

**Comment by dduportal** [comment]
Hi @t0b1nux : it is not that simple. Without taking in account specific pythont part, how to handle docker raw level arguments like inline socket adress : 
```
docker -H tcp://marcel-penderie-chef.io.com:8000 info
```
?

**Comment by t0b1nux** [comment]
@dduportal Yeah, after thinking about it, I should agree that the shell itself isn't very prepared for inversed command. Maybe an idea for a future version of POSIX ;) ?

**Comment by dduportal** [comment]
The troll, long deep inside want to say : "why not Go ?" :)

**Comment by brouberol** [comment]
Cause I was in a train, and I can Python in my sleep. A concurrent go implementation also exists https://github.com/dgageot/marcel.

**Comment by t0b1nux** [comment]
@dduportal If we go that way ? Why not a thread-safe, security-oriented language such as Rust ?
Ah no, forget it, its' the french government...

**Comment by jlevesy** [comment]
Look a troll in a troll ! I definitely love this thread !

On Sat, Jan 23, 2016, 11:06 AM Simon THOBY <notifications@github.com> wrote:

> @dduportal <https://github.com/dduportal> If we go that way ? Why not a
> thread-safe, security-oriented language such as Rust ?
> Ah no, forget it, its' the french government...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brouberol/marcel/issues/10#issuecomment-174167062>.
>
-- 
Julien Levesy

**Comment by t0b1nux** [comment]
Adding this would be too complex and imply using many symlinks and could override existing binaries. So I close this
