### ISSUE TITLE
Add gh-pages CNAME support back

### ISSUE THREAD

**Issue by t0b1nux** [brouberol/marcel#15]
"To use your custom domain, whether you're setting up an apex domain or a subdomain, you need to remove the CNAME file from the other repository in which it's used." -> I've done that
" After you have done this, you will also need to push again to trigger a new page build." -> I couldn't do this but you can

TL;DR: Trigger a new build by pushing something onto the gh-pages branch, please

**Comment by brouberol** [comment]
should be ok

**Comment by t0b1nux** [comment]
It is, you could close now. Thanks !

**Comment by t0b1nux** [comment]
Because I forgot to add a point in my DNS, I will need to wait for dns cache to reload. Hopefully, I've added a redirection on my webserver for that time. Sorry for the inconvenience.
