### ISSUE TITLE
Mac OS X support

### ISSUE THREAD

**Issue by t0b1nux** [brouberol/marcel#16]
What about HFS+ ? Does it handle well our naming scheme ? (aka RecetteÀMarcel ?)
I don't use or own apple computers but many does and we shall be compliant with uncompliant (even broken) filesystems if many uses them.

**Comment by brouberol** [comment]
I'm on Linux. Is anyone on mac? @jlevesy, @dduportal ?

**Comment by t0b1nux** [comment]
Wait a moment... I'm stupid! Can mac OS X run natively docker containers ? Not sure of it.
So why the hell would they need to be able to run marcel if the underlying backend doesn't even exist ?

**Comment by t0b1nux** [comment]
If mac users use Linux in a VM, Mac OS X doesn't need marcel.
