### ISSUE TITLE
Need unit tests for translations

### ISSUE THREAD

**Issue by brouberol** [brouberol/marcel#22]
Soyons serieux.

**Comment by t0b1nux** [comment]
Unit tests ? Then we need also a travis infrastructure for CI ;)

**Comment by thomas-maurice** [comment]
:+1: for the travis and automatic push on PyPi !

**Comment by brouberol** [comment]
I can take care of the unit tests (if no-one is interested), if someone takes care of travis.

**Comment by t0b1nux** [comment]
What exactly do you want to do ? Automatic testing with virtual images to see if the result is the same as using original docker ?

**Comment by brouberol** [comment]
I was thinking more about marcel syntax --> docker syntax tests. 

Example: testing that ``marcel chauffe`` is translated to ``docker run``, etc.

**Comment by t0b1nux** [comment]
Right, this shoul be easier to test and probably more efficient

**Comment by brouberol** [comment]
Fixed by  #32
