### ISSUE TITLE
Vector graphics logo

### ISSUE THREAD

**Issue by t0b1nux** [brouberol/marcel#25]
Is there somebody with graphics competences to redesign the logo using scalable vector graphics ? Because the current one (https://raw.githubusercontent.com/brouberol/marcel/master/logo.png) is somewhat rasterized.

**Comment by jkneb** [comment]
Guys, actually you have a screenshot version of the logo. Give me a moment to export the svg file.

**Comment by jkneb** [comment]
Ok first here's a better exported png image

<img width="870" alt="marcel-logo" src="https://cloud.githubusercontent.com/assets/805719/12532757/09b199ae-c21c-11e5-8d7e-72170ae48d40.png">

**Comment by t0b1nux** [comment]
@jkneb Great ! thanks you.

**Comment by jkneb** [comment]
I also have the svg file but github won't let me import it here... the png just above is still way better than the other one though :ghost:

**Comment by t0b1nux** [comment]
Thanks, we will take care of the svg later. Can somebody actually on a real computer (not just a tablet like me currently) make a PR replacing the logo.png with ther hiher quality one ?

**Comment by jkneb** [comment]
Pushed on the gh-page already.

**Comment by jkneb** [comment]
And updated also the readme file on master

**Comment by brouberol** [comment]
Can we close this one?

**Comment by jkneb** [comment]
Yeap I guess so.
