### ISSUE TITLE
Setup Travis automatic tests

### ISSUE THREAD

**Issue by brouberol** [brouberol/marcel#26]
Needs #22 to be resolved first.

**Comment by t0b1nux** [comment]
Don't know how to use travis but willing to help and ready to learn :)

**Comment by thomas-maurice** [comment]
@brouberol only you can setup Travis tests and build because the travis acount is linked to YOUR account. That's why only you can do it.

Also an automatic push on pypi would be awesome :)

Example travis build for a python package can be found there : https://github.com/thomas-maurice/dnsbin-cli

**Comment by brouberol** [comment]
Fixed by #32
