### ISSUE TITLE
Python is not France compatible

### ISSUE THREAD

**Issue by Nicals** [brouberol/marcel#28]
This project should be written using WinDev which is more in the Bidochon way of life.

```
(o )( o)
```

**Comment by brouberol** [comment]
Marcel is not just an implementation. It aims at becoming a standard. If you feel that WinDev would be more baguette-and-camembert, then please, implement it and release it back to the people. 

![bidoche](http://static.comicvine.com/uploads/scale_small/0/77/1318583-kador.jpg)
