### ISSUE TITLE
Ajouter un LISEZMOI.md

### ISSUE THREAD

**Issue by Oros42** [brouberol/marcel#29]
Afin que Marcel puisse être utilisé par des Français ne parlant pas anglais, il serait judicieux d'ajouter un LISEZMOI.md avec la traduction du fichier README.md.

**Comment by t0b1nux** [comment]
Exact! des suggestions de traduction ?

**Comment by t0b1nux** [comment]
Suggestion de traduction: 

# Marcel, docker à la française

![logo](https://brouberol.github.io/marcel/images/logo/marcel-logo.png)

Marcel est une enveloppe française qui se base sur l'interface de commande docker et a pour but de remplacer docker, afin de préparer le chemin pour le nouvel SO souverain Français.

## Exemples

* ``docker run`` → ``marcel chauffe``
* ``docker images`` → ``marcel cederoms``
* ``docker login`` → ``marcel vos-papiers``
* ``docker logs`` → ``marcel bûches``
* ``docker pause`` → ``marcel rtt``
* ``docker suspend`` → ``marcel grève``
* ``docker tag`` → ``marcel graffiti``
* ``docker rmi`` → ``marcel rsa``

## RecetteÀMarcel

Pour des raisons évidentes, ``Dockerfile`` ne nous semble pas assez souverain, c'est pourquoi marcel utilises ``RecetteÀMarcel`` en lieu et place de ``Dockerfile``.

Pour que cela fonctionne, il vous suffit d'intégrer le fichier ``RecetteÀMarcel`` dans votre dossier courant où vous èxécuterez ensuitee ``marcel construis``. Et voilà, vous pouvez travailler !

**Comment by t0b1nux** [comment]
Des corrections, idées ou suggestions ?

**Comment by t0b1nux** [comment]
https://github.com/brouberol/marcel/pull/30

**Comment by francisbesset** [comment]
Le nommer `LISEZ-MOI.rtf` est plus en vogue en France.

**Comment by StyXman** [comment]
P'tet le renommer `LISEZ-MOI.mrd`?

**Comment by t0b1nux** [comment]
Qu'en pense l'Académie française ?

**Comment by motet-a** [comment]
Je metterai une majuscule à « Docker » et à « Marcel », mais j’aime bien.
