### ISSUE TITLE
Bash version

### ISSUE THREAD

**Issue by loliee** [brouberol/marcel#46]
Y pas une version light en bash ?

Car la je traverse du :snake: pour pas grand chose ...

Well done c'est rigolo les gars ;)

**Comment by brouberol** [comment]
Le premier commit de https://github.com/dgageot/marcel était en bash (https://github.com/dgageot/marcel/commit/d08b427a2a35f5576e478369b5227cb8b11988fd)

**Comment by brouberol** [comment]
Au passage, personne n'a jamais lu de python pour rien. C'est comme dire "j'ai oeuvré pour un monde meilleur pour rien", ç'a n'a pas de sens.

![hoax](https://i.imgur.com/up6yu.jpg)

**Comment by loliee** [comment]
Je confirme, dix ans de python derrière moi et je sais pourquoi ;)
Mais pour lancer pour lancer mon `marcel chauffe` je voulais pas sortir ma mitraillette.

Pour le python j'ai lu rapidement le votre et je comprends pas les `u` devant les docstrings ?
Concernant la version tu pourrais la mettre dans un fichier `__init__.py`, check (Django)[https://github.com/django/django/blob/master/django/__init__.py#L5] et tu peux l'import dans le `setup.py` pas la peine de `read()` tout le fichier et la passer a la regexp... 
Le `if` [suivant](https://github.com/brouberol/marcel/blob/master/marcel.py#L101-L113) est pas très french glamour :kiss:, codez sur 80 cols on peux faire les codes review sur tél portable ;)

Cheers,
For the future french sovereign operating system.

**Comment by brouberol** [comment]
Le ``u`` devant les docstring est probablement inutile.
En ce qui concerne le ``__version__``, j'ai tendance à le faire comme ça plutôt que dans l'``__init__``, parce que je j'ai trop bossé avec des packages qui avaient besoin d'autres packages au setup, et donc avec lesquels l'import de ``__version__`` explosait (numpy & scipy, wink wink).  C'est vrai qu'avec marcel, fi de ces problèmes..

Je vais faire un petit commit pour cleaner tout ça :)

Par contre, je suis contre la limite à 80 caractcères, après des années de suivi de la PEP8. J'ai tendance à mettre une limite à 92. 80, c'est vraiment tout petit. Pardon pour les reviewers sur mobile :/

**Comment by brouberol** [comment]
En ce qui concerne la limite à 92, j'ai suivi le [conseil](https://www.youtube.com/watch?v=wf-BqAjZb8M) de Raymond Hettinger. Il est plutôt calé en python l'animal :smiley_cat:

**Comment by loliee** [comment]
@brouberol merci pour le lien, du coup grâce à Marcel je vais écouter Raymond :)

**Comment by t0b1nux** [comment]
Sinon, quite à supporter du shell, autanr en gérer un POSIX. À moins que vous ne connaissiez un shell français ?

**Comment by thomas-maurice** [comment]
frensh, par @brouberol :)

**Comment by brouberol** [comment]
Omg. Combining both of them would be the ultimate private French joke.
--
B
 
 
On Wed, Feb 3, 2016, at 08:43 PM, Thomas Maurice wrote:
> frensh, par @brouberol[1] :)


> —
> Reply to this email directly or view it on GitHub[2]. 


>  
 


Links:

  1. https://github.com/brouberol
  2. https://github.com/brouberol/marcel/issues/46#issuecomment-179421456
