### ISSUE TITLE
Marcel doit soutenir les gilets jaunes

### ISSUE THREAD

**Issue by alexislefebvre** [brouberol/marcel#63]
Je propose que le marcel soit coloré en jaune pour les jours à venir.

Proposition :

<img width="648" alt="gilet_jaune" src="https://user-images.githubusercontent.com/2071331/48906438-bd9b1e00-ee64-11e8-9090-6fd1608d0327.png">

Voir #47

**Comment by brouberol** [comment]
Je ne suis pas personnellement un grand soutien des gilets jaunes, MAIS, je ne peux pas refuser une suggestion qui me fait autant rire. Si tu ouvres une PR avec le remplacement de l'image, je merge.
