### ISSUE TITLE
Add examples to Readme

### ISSUE THREAD

**Issue by brouberol** [brouberol/marcel#8]
People need to be able to understand why Marcel is such a deal breaker. We need examples in the Readme

**Comment by t0b1nux** [comment]
Why not add link to show that we are compliant with the specification asked by the parliament? Something like 'SS (Souverain Specification) v0.1 compliant'.
And what about explaining how security-oriented people we are: helping gouvernement secret agencies parse our infrastructures to help us make them more secure by copying every Marcelfile on the 'cloud souverain' ?
This should improve our public status

**Comment by t0b1nux** [comment]
I've added https://github.com/brouberol/marcel/commit/fd85fff93fe89152b2e5524aea139570702752f4 & https://github.com/brouberol/marcel/commit/65679f3533d51b2c4c21d1002348786f7a7a91e2. What do you think ?

**Comment by brouberol** [comment]
Perfect :)
